-- REDEACHADOS BR Publisher V5.5.4
-- Persistência da automação Instagram comentário -> Direct

create extension if not exists pgcrypto;

create table if not exists public.reel_links (
  id uuid primary key default gen_random_uuid(),
  instagram_media_id text unique not null,
  sku text,
  product_name text not null,
  product_url text not null,
  keyword text not null default 'QUERO',
  auto_dm_enabled boolean not null default true,
  public_reply_enabled boolean not null default true,
  public_reply_text text not null default 'Enviei o link no seu Direct ✅',
  dm_message_template text not null default 'Oi! 👋 Aqui está o link do produto que você viu no nosso Reel: {link}',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reel_links_sku_idx on public.reel_links (sku);
create index if not exists reel_links_active_idx on public.reel_links (active);

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reel_links_set_updated_at on public.reel_links;
create trigger reel_links_set_updated_at
before update on public.reel_links
for each row execute function public.update_updated_at_column();

create table if not exists public.dm_log (
  id bigint generated by default as identity primary key,
  comment_id text unique not null,
  instagram_media_id text not null,
  instagram_user_id text,
  instagram_username text,
  comment_text text,
  product_url text,
  status text not null default 'received' check (status in ('received','sent','ignored','error')),
  meta_response jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create index if not exists dm_log_media_idx on public.dm_log (instagram_media_id);
create index if not exists dm_log_created_at_idx on public.dm_log (created_at desc);

alter table public.reel_links enable row level security;
alter table public.dm_log enable row level security;
-- Sem policies públicas: o Publisher usa apenas a Secret key no backend do Render
-- e a Edge Function usa credenciais server-side do próprio Supabase.
